server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://board-db:3306/board_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

