server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://board-db:3306/board_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
user-service:
  url: http://${USER_API_HsOST:user-service}:${USER_API_PORT:8081}
